services:
  debian-test-image:
    build:
      context: .
      dockerfile: ./test-containers/debian/Dockerfile
    container_name: debian-test-container
    volumes:
      - .:/usr/src
      - $HOME/test_results:/test_results
    environment:
      - ZEPHYR_SDK_VERSION=0.17.0
      - ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-0.17.0
    stdin_open: true
    tty: true

  ubuntu-test-image:
    build:
      context: .
      dockerfile: ./test-containers/ubuntu/Dockerfile
    container_name: ubuntu-test-container
    volumes:
      - .:/usr/src
      - $HOME/test_results:/test_results
    environment:
      - ZEPHYR_SDK_VERSION=0.17.0
      - ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-0.17.0
    stdin_open: true
    tty: true
    
  arch-test-image:
    build:
      context: .
      dockerfile: ./test-containers/arch/Dockerfile
    container_name: arch-test-container
    volumes:
      - .:/usr/src
      - $HOME/test_results:/test_results
    environment:
      - ZEPHYR_SDK_VERSION=0.17.0
      - ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-0.17.0
    stdin_open: true
    tty: true
