services:
  zephyr:
    build:
      context: .
      dockerfile: ./test-containers/debian/Dockerfile
    container_name: nucleof429zi_cicd
    volumes:
      - .:/usr/src
    environment:
      - ZEPHYR_SDK_VERSION=0.17.0
      - ZEPHYR_SDK_INSTALL_DIR=/opt/toolchains/zephyr-sdk-0.17.0
    stdin_open: true
    tty: true