name: CI/CD for Nucleo F429ZI

on:
  push:
    branches:
      - main  # Runs when pushing to 'main'
  pull_request:
    branches:
      - main  # Runs on PRs to 'main'
  workflow_dispatch:  # Allows manual runs

jobs:
  build-and-flash:
    runs-on: self-hosted  # Uses your Debian runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python Virtual Environment
        run: |
          cd /home/eo/nucleof429zi_cicd
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt  # Ensure dependencies are installed

      - name: Build Firmware
        run: |
          source /home/eo/nucleof429zi_cicd/venv/bin/activate
          west build -p always -b nucleo_f429zi /home/eo/nucleof429zi_cicd

      - name: Flash to Nucleo Board
        run: |
          source /home/eo/nucleof429zi_cicd/venv/bin/activate
          west flash --runner openocd
