name: Build Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: nucleof429zi_cicd

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: nucleof429zi_cicd
          toolchains: arm-zephyr-eabi

      - name: Build firmware
        working-directory: nucleof429zi_cicd
        shell: bash
        run: |
          EXTRA_TWISTER_FLAGS="--short-build-path -O /tmp/twister-out"
          west twister -T app -v --inline-logs --integration $EXTRA_TWISTER_FLAGS

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: /tmp/twister-out/**/*

