name: Check Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: nucleof429zi_cicd

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: nucleof429zi_cicd
          toolchains: arm-zephyr-eabi

      - name: Install Check framework
        run: |
          sudo apt update
          sudo apt install -y check

      - name: Build Check tests
        working-directory: nucleof429zi_cicd
        run: |
          west build -b native_posix app -- -DCONFIG_TESTING_CHECK=y

      - name: Run Check tests
        working-directory: nucleof429zi_cicd/build
        run: |
          ./zephyr/zephyr.elf > test_output.log
          cat test_output.log

      - name: Upload Check Test Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: check-test-results
          path: nucleof429zi_cicd/build/test_output.log
