name: Check Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  check-tests:
    runs-on: ubuntu-22.04
    timeout-minutes: 5 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: nucleof429zi_cicd

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: nucleof429zi_cicd
          toolchains: arm-zephyr-eabi

      - name: Install Check framework
        run: |
          sudo apt update
          sudo apt install -y check

      - name: Build Check tests
        working-directory: nucleof429zi_cicd
        run: |
          west build -b native_posix app 

      - name: Run Check tests
        working-directory: nucleof429zi_cicd/build
        run: |
          echo "Running zephyr.elf with increased logging..."
          ./zephyr/zephyr.elf -DCONFIG_LOG=y -DCONFIG_LOG_DEFAULT_LEVEL=4 > test_output.log 2>&1 &
          sleep 5  # Add some time for the process to start
          tail -n 100 test_output.log  # Tail the last 100 lines to check logs

      - name: Upload Check Test Logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: check-test-results
          path: nucleof429zi_cicd/build/test_output.log
