name: GitHub-hosted ztests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: nucleof429zi_cicd

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: nucleof429zi_cicd
          toolchains: arm-zephyr-eabi

      - name: Generate Timestamped Folder Name
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Ensure Twister Output Directory Exists
        run: mkdir -p ${{ github.workspace }}/${{ env.TIMESTAMP }}

      - name: Build firmware
        working-directory: nucleof429zi_cicd
        shell: bash
        run: |
          EXTRA_TWISTER_FLAGS="--short-build-path -O ${{ github.workspace }}/${{ env.TIMESTAMP }}"
          west twister -T app -v --inline-logs --integration $EXTRA_TWISTER_FLAGS
      
      - name: Run Twister Tests
        working-directory: nucleof429zi_cicd
        shell: bash
        run: |
          EXTRA_TWISTER_FLAGS="--verbose --short-build-path -O ${{ github.workspace }}/${{ env.TIMESTAMP }}"
          west twister -T tests -v --inline-logs --integration $EXTRA_TWISTER_FLAGS

      - name: Compress Twister Output (Optional)
        run: tar -czf ${{ github.workspace }}/${{ env.TIMESTAMP }}.tar.gz -C ${{ github.workspace }}/${{ env.TIMESTAMP }} .

      - name: Upload Compressed Twister Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: twister-test-results-${{ matrix.os }}-${{ env.TIMESTAMP }}
          path: ${{ github.workspace }}/${{ env.TIMESTAMP }}.tar.gz
          retention-days: 7
