name: Docker Self-hosted Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  self-hosted-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and start container with docker-compose
        run: |
          docker compose up --build ubuntu-test-image

      - name: Wait for the container to start
        run: |
          sleep 10 
