name: Self-hosted runner -- Ubuntu latest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  self-hosted-runner:
    runs-on: [self-hosted, ubuntu-runner]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debugging current working directory and contents
        run: |
          echo "Current working directory:"
          pwd
          echo "Contents of the current directory:"
          ls -la

      - name: Run Twister Tests
        run: |
          # Activate the virtual environment
          source /opt/venv/bin/activate

          # Create results directory with proper permissions
          mkdir -p /home/gha/twister_results

          # Run Twister tests
          west twister -T tests --verbose --integration --outdir twister_results