name: Self-hosted runner -- Ubuntu latest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  self-hosted-runner:
    runs-on: [self-hosted, ubuntu-runner]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debugging current working directory and contents
        run: |
          echo "Current working directory:"
          pwd
          echo "Contents of the current directory:"
          ls -la

      - name: Start Docker container
        run: docker compose up -d

      - name: Run tests inside container
        run: docker compose exec debian bash -c "/entrypoint.sh"

      - name: Upload Twister test results
        uses: actions/upload-artifact@v4
        with:
          name: twister-test-results
          path: /home/gha/twister_results/
          retention-days: 7
