name: Self-hosted runner -- Debian latest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  self-hosted-runner:
    runs-on: self-hosted

    steps:
      - name: Cleanup repository before checkout
        run: |
          rm -rf $GITHUB_WORKSPACE/* || true
          chown -R $USER:$USER $GITHUB_WORKSPACE
          chmod -R u+rwX $GITHUB_WORKSPACE
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and start container with docker-compose
        run: |
          docker compose up --build debian-test-image