name: Self-hosted runner -- Ubuntu latest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  self-hosted-runner:
    runs-on: [self-hosted, ubuntu-runner]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload Twister test results
        uses: actions/upload-artifact@v4
        with:
          name: twister-test-results
          path: twister_results/
          retention-days: 7
