name: Self-hosted runner -- Ubuntu latest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  self-hosted-runner:
    runs-on: [self-hosted, ubuntu-runner]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show running containers
        run: docker ps -a

      - name: Run Twister tests inside the running container
        run: docker compose exec ubuntu bash -c "west twister -T tests --verbose --integration --outdir /home/gha/twister_results"

      - name: Show test result files inside the container
        run: docker compose exec ubuntu ls -l /home/gha/twister_results/

      - name: Upload Twister test results
        uses: actions/upload-artifact@v4
        with:
          name: twister-test-results
          path: /home/gha/twister_results/
          retention-days: 7
