name: Self-hosted runner -- Ubuntu latest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  self-hosted-runner:
    runs-on: [self-hosted, ubuntu-runner]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Twister tests
        run: |
          west twister -T tests --verbose --integration