name: Self-hosted runner -- Ubuntu latest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  self-hosted-runner:
    runs-on: [self-hosted, ubuntu-runner]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show current working directory
        run: |
          echo "Current working directory:"
          pwd  # Show the current working directory

      - name: List files in current directory
        run: |
          echo "Listing files in the current directory:"
          ls -l  # List the files in the current working directory
          