name: Self-hosted runner -- Debian latest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  self-hosted-runner:
    runs-on: [self-hosted, debian-runner]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debugging current working directory and contents
        run: |
          echo "Current working directory:"
          pwd
          echo "Contents of the current directory:"
          ls -la

      - name: Set up West workspace
        run: |
          cd $HOME
          if [ ! -d ".west" ]; then
            west init -m https://github.com/ericodle/nucleof429zi_cicd
          fi
          west update

      - name: Run Twister tests
        run: |
          cd $HOME/nucleof429zi_cicd
          mkdir -p $HOME/twister_results
          west twister -T tests --verbose --integration --outdir $HOME/twister_results
