name: Self-hosted runner -- Debian latest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  self-hosted-runner:
    runs-on: [self-hosted, debian-runner, ubuntu-runner, arch-runner]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debugging current working directory and contents
        run: |
          echo "Current working directory:"
          pwd
          echo "Contents of the current directory:"
          ls -la

      - name: Set up West workspace
        run: |
          cd $HOME
          if [ ! -d ".west" ]; then
            west init -m https://github.com/ericodle/nucleof429zi_cicd
          fi
          west update

      - name: Run Twister tests
        run: |
          TEMP_DIR=$(mktemp -d)  # Create a temporary directory
          echo "Using temp directory: $TEMP_DIR"
          cd $HOME/nucleof429zi_cicd
          west twister -T tests --verbose --integration --outdir $TEMP_DIR

          # Export TEMP_DIR as an environment variable for later steps
          echo "TWISTER_RESULTS=$TEMP_DIR" >> $GITHUB_ENV

      - name: Upload Twister test results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: twister-results
          path: ${{ env.TWISTER_RESULTS }}/**
          retention-days: 7
