name: Self-hosted runner -- Ubuntu latest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  self-hosted-runner:
    runs-on: [self-hosted, ubuntu-runner]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debugging current working directory and contents
        run: |
          echo "Current working directory:"
          pwd
          echo "Contents of the current directory:"
          ls -la

      - name: Set up Zephyr workspace and run Twister tests
        run: |
          # Activate the virtual environment
          source /opt/venv/bin/activate

          # Debug: Check if west is installed and available
          echo "Checking west version..."
          west --version

          # Initialize the West workspace if not already initialized
          if [ ! -d ".west" ]; then
            echo "Initializing west workspace..."
            west init -m https://github.com/ericodle/nucleof429zi_cicd
          else
            echo "West workspace already initialized."
          fi

          # Update West to make sure it's up to date
          echo "Updating west..."
          west update

          # Debug: Check if twister is recognized as a valid command
          echo "Checking if twister command is available..."
          west --help | grep twister || echo "Twister command not found"

          # Check if twister subcommand is available
          if ! west twister --help > /dev/null 2>&1; then
            echo "Twister command is not available. Please ensure the Zephyr workspace is correctly set up."
            exit 1
          fi

          # Create results directory with proper permissions
          mkdir -p /home/gha/twister_results

          # Run Twister tests
          echo "Running Twister tests..."
          west twister -T tests --verbose --integration --outdir twister_results