name: ZTests with Ubuntu environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]  # Use Ubuntu instead of Debian

    runs-on: ubuntu-latest  # Use Ubuntu as the runner

    steps:
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y python3 python3-pip git cmake ninja-build gperf \
          ccache dfu-util dtc libffi-dev libssl-dev file wget xz-utils \
          make gcc gcc-multilib g++-multilib libsdl2-dev python3-dev \
          python3-setuptools python3-tk python3-wheel xz-utils unzip \
          tar curl sudo udev

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: nucleof429zi_cicd

      - name: Set up Python
        run: |
          pip3 install --upgrade pip
          pip3 install -r nucleof429zi_cicd/requirements.txt

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: nucleof429zi_cicd
          toolchains: arm-zephyr-eabi

      - name: Build firmware
        working-directory: nucleof429zi_cicd
        shell: bash
        run: |
          EXTRA_TWISTER_FLAGS="--short-build-path -O /tmp/twister-out"
          west twister -T app -v --inline-logs --integration $EXTRA_TWISTER_FLAGS

      - name: Run Twister Tests
        working-directory: nucleof429zi_cicd
        shell: bash
        run: |
          EXTRA_TWISTER_FLAGS=" --verbose --short-build-path -O /tmp/twister-out"
          west twister -T tests -v --inline-logs --integration $EXTRA_TWISTER_FLAGS

      - name: Check Twister Output Files
        run: |
          echo "Listing twister-out directory:"
          ls -R /tmp/twister-out

      - name: Upload Twister Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: twister-test-results-${{ matrix.os }}
          path: |
            /tmp/twister-out/**/*

      - name: Upload Logs for Deployment
        if: always()
        run: |
          mkdir -p deploy/logs
          if [ -d "/tmp/twister-out" ]; then
            mv /tmp/twister-out deploy/logs/
          else
            echo "No Twister output to move"
          fi
