name: ZTests with Ubuntu 22 Environment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: nucleof429zi_cicd

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: nucleof429zi_cicd
          toolchains: arm-zephyr-eabi

      # Clean previous west initialization and reinitialize workspace if needed
      - name: Clean previous west initialization
        run: |
          echo "Checking if .west exists"
          if [ -d "$PWD/nucleof429zi_cicd/.west" ]; then
            echo "Removing existing .west directory..."
            rm -rf "$PWD/nucleof429zi_cicd/.west"
          else
            echo ".west directory does not exist, skipping cleanup."
          fi

      # Initialize Zephyr workspace
      - name: Initialize Zephyr workspace
        run: |
          echo "Checking if Zephyr workspace is initialized..."
          WEST_DIR="$PWD/nucleof429zi_cicd/.west"
          if [ ! -d "$WEST_DIR" ]; then
            echo "Initializing Zephyr workspace..."
            west init -l nucleof429zi_cicd --mf west.yml
          else
            echo "Zephyr workspace already initialized."
          fi

      # Step to ensure the twister-out directory exists
      - name: Ensure twister-out directory exists
        run: |
          mkdir -p /tmp/twister-out

      # Build firmware
      - name: Build firmware
        working-directory: nucleof429zi_cicd
        shell: bash
        run: |
          EXTRA_TWISTER_FLAGS="--short-build-path -O /tmp/twister-out"
          west twister -T app -v --inline-logs --integration $EXTRA_TWISTER_FLAGS

      # Run Twister tests
      - name: Run Twister Tests
        working-directory: nucleof429zi_cicd
        shell: bash
        run: |
          EXTRA_TWISTER_FLAGS=" --verbose --short-build-path -O /tmp/twister-out"
          west twister -T tests -v --inline-logs --integration $EXTRA_TWISTER_FLAGS

      # Save logs locally
      - name: Save Twister Logs Locally
        run: |
          mkdir -p ~/twister_logs
          echo "Saving Twister logs locally..."
          cp -r /tmp/twister-out ~/twister_logs/

      # Check Twister output files
      - name: Check Twister Output Files
        run: |
          echo "Listing twister-out directory:"
          ls -R /tmp/twister-out

      # Upload Twister test results
      - name: Upload Twister Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: twister-test-results-${{ matrix.os }}
          path: |
            /tmp/twister-out/**/*

      # Upload logs for deployment
      - name: Upload Logs for Deployment
        if: always()
        run: |
          mkdir -p deploy/logs
          rm -rf deploy/logs/twister-out  # Remove the existing twister-out directory
          mkdir -p deploy/logs/twister-out  # Create a fresh directory for new logs
          if [ -d "/tmp/twister-out" ]; then
            mv /tmp/twister-out deploy/logs/twister-out/
          else
            echo "No Twister output to move"
          fi
