name: ZTests Run on GitHub

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: nucleof429zi_cicd

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: nucleof429zi_cicd
          toolchains: arm-zephyr-eabi

      - name: Build firmware
        working-directory: nucleof429zi_cicd
        shell: bash
        run: |
          EXTRA_TWISTER_FLAGS="--short-build-path -O /tmp/twister-out"
          west twister -T app -v --inline-logs --integration $EXTRA_TWISTER_FLAGS

      - name: Run Twister Tests
        working-directory: nucleof429zi_cicd
        shell: bash
        run: |
          EXTRA_TWISTER_FLAGS="--verbose --short-build-path -O /tmp/twister-out"
          west twister --all $EXTRA_TWISTER_FLAGS

      - name: Check Twister Output Files
        run: |
          echo "Listing twister-out directory:"
          ls -R /tmp/twister-out || echo "No output found"

      - name: Upload Twister Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: twister-test-results-${{ matrix.os }}
          path: /tmp/twister-out/**/*
          
      - name: Upload Logs for Deployment
        if: always()
        run: |
          mkdir -p deploy/logs
          if [ -d "/tmp/twister-out" ]; then
            mv /tmp/twister-out deploy/logs/
          else
            echo "No Twister output to move"
          fi
